export const DEFAULT_EVENTS = 'DEFAULT_EVENTS';
export const UPDATE_EVENT_LIST = 'UPDATE_EVENT_LIST';

export const DEFAULT_INITIATIVES = 'DEFAULT_INITIATIVES';
export const UPDATE_INITIATIVES_LIST = 'UPDATE_INITIATIVES_LIST';