export const DEFAULT_EVENTS = 'DEFAULT_EVENTS';
export const UPDATE_EVENT_LIST = 'UPDATE_EVENT_LIST';

export const GET_EVENTDETAILS = 'GET_EVENTDETAILS';
export const AUTHORIZED_USER = 'AUTHORIZED_USER';
export const RESET_TO_DEFAULT = "RESET_TO_DEFAULT";
export const INVALID_LOGIN = "Please enter correct email/password";
export const DEFAULT_EVENT = 'DEFAULT_EVENT';
export const DEFAULT_INITIATIVES = 'DEFAULT_INITIATIVES';
export const CREATE_AN_INITIATIVE = "CREATE_AN_INITIATIVE";
