export const GET_EVENTS = "https://develop-shesmashes-thehub.herokuapp.com/api/events/list-events";
export const LOGGIN_USER = "https://develop-shesmashes-thehub.herokuapp.com/api/users/login";
export const GET_EVENTDETAILURL = "https://develop-shesmashes-thehub.herokuapp.com/api/events";
export const GET_INITIATIVES = "https://develop-shesmashes-thehub.herokuapp.com/api/initiatives";
export const CREATE_NEW_INITIATIVE = "https://develop-shesmashes-thehub.herokuapp.com/api/initiatives";
export const GET_TASKS = "https://develop-shesmashes-thehub.herokuapp.com/api/tasks/list-pending-tasks";
export const UPDATE_TASK = "https://develop-shesmashes-thehub.herokuapp.com/api/tasks";
export const CREATE_NEW_EVENT = "https://develop-shesmashes-thehub.herokuapp.com/api/events";
export const APPROVED_INITIATIVES = 'https://develop-shesmashes-thehub.herokuapp.com/api/initiatives?filter={"where":{"status" : "approved"}}';
export const VERIFY_USER = 'https://develop-shesmashes-thehub.herokuapp.com/api/users?filter=';
export const SWAGGER_SPEC_URL = "https://develop-shesmashes-thehub.herokuapp.com/explorer/swagger.json";
export const ALL_CATEGORIES = "https://develop-shesmashes-thehub.herokuapp.com/api/categories";
