export const GET_EVENTS = "http://localhost:4000/api/events/list-events";
export const LOGGIN_USER = "http://localhost:4000/api/users/login";
export const GET_EVENTDETAILURL = "http://localhost:4000/api/events";
export const GET_INITIATIVES = "http://localhost:4000/api/initiatives";
export const CREATE_NEW_INITIATIVE = "http://localhost:4000/api/initiatives";
export const GET_TASKS = "http://localhost:4000/api/tasks/list-pending-tasks";
export const UPDATE_TASK = "http://localhost:4000/api/tasks";
export const CREATE_NEW_EVENT = "http://localhost:4000/api/events";
export const APPROVED_INITIATIVES = 'http://localhost:4000/api/initiatives?filter={"where":{"status" : "approved"}}';
export const VERIFY_USER = 'http://localhost:4000/api/users?filter=';
export const SWAGGER_SPEC_URL = "http://localhost:4000/explorer/swagger.json";
export const ALL_CATEGORIES = "http://localhost:4000/api/categories";
